Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/miniconda3/lib/python3.8/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/miniconda3/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/miniconda3/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/opt/miniconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/miniconda3/lib/python3.8/site-packages/nbclient/client.py", line 540, in async_execute
    await self.async_execute_cell(
  File "/opt/miniconda3/lib/python3.8/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/miniconda3/lib/python3.8/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
mp4_file_path = "../../exports/examples/connectivity.mp4"
anim_conn.save(mp4_file_path, fps=3, dpi=300)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-14-5fb74e5a6de9>[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0mmp4_file_path[0m [0;34m=[0m [0;34m"../../exports/examples/connectivity.mp4"[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m [0manim_conn[0m[0;34m.[0m[0msave[0m[0;34m([0m[0mmp4_file_path[0m[0;34m,[0m [0mfps[0m[0;34m=[0m[0;36m3[0m[0;34m,[0m [0mdpi[0m[0;34m=[0m[0;36m300[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;31mNameError[0m: name 'anim_conn' is not defined
NameError: name 'anim_conn' is not defined

