Traceback (most recent call last):
  File "/Users/mpin/opt/miniconda3/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/mpin/opt/miniconda3/lib/python3.8/site-packages/nbclient/client.py", line 1082, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/mpin/opt/miniconda3/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/mpin/opt/miniconda3/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/mpin/opt/miniconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/mpin/opt/miniconda3/lib/python3.8/site-packages/nbclient/client.py", line 535, in async_execute
    await self.async_execute_cell(
  File "/Users/mpin/opt/miniconda3/lib/python3.8/site-packages/nbclient/client.py", line 827, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/mpin/opt/miniconda3/lib/python3.8/site-packages/nbclient/client.py", line 735, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
num_steps = 50
smaller_epoch = epochs.skip_n_steps(num_steps)
smaller_epoch.get_data().shape
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
[0;32m<ipython-input-14-2117361c8207>[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0mnum_steps[0m [0;34m=[0m [0;36m50[0m[0;34m[0m[0;34m[0m[0m
[1;32m      2[0m [0msmaller_epoch[0m [0;34m=[0m [0mepochs[0m[0;34m.[0m[0mskip_n_steps[0m[0;34m([0m[0mnum_steps[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 3[0;31m [0msmaller_epoch[0m[0;34m.[0m[0mget_data[0m[0;34m([0m[0;34m)[0m[0;34m.[0m[0mshape[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;31mAttributeError[0m: 'EvokedArray' object has no attribute 'get_data'
AttributeError: 'EvokedArray' object has no attribute 'get_data'

