Traceback (most recent call last):
  File "/Users/mpin/opt/miniconda3/lib/python3.8/site-packages/nbclient/client.py", line 604, in _async_poll_for_reply
    msg = await ensure_async(self.kc.shell_channel.get_msg(timeout=new_timeout))
  File "/Users/mpin/opt/miniconda3/lib/python3.8/site-packages/nbclient/util.py", line 85, in ensure_async
    result = await obj
  File "/Users/mpin/opt/miniconda3/lib/python3.8/site-packages/jupyter_client/asynchronous/channels.py", line 48, in get_msg
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mpin/opt/miniconda3/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/mpin/opt/miniconda3/lib/python3.8/site-packages/nbclient/client.py", line 1082, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/mpin/opt/miniconda3/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/mpin/opt/miniconda3/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/mpin/opt/miniconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/mpin/opt/miniconda3/lib/python3.8/site-packages/nbclient/client.py", line 535, in async_execute
    await self.async_execute_cell(
  File "/Users/mpin/opt/miniconda3/lib/python3.8/site-packages/nbclient/client.py", line 811, in async_execute_cell
    exec_reply = await self.task_poll_for_reply
  File "/Users/mpin/opt/miniconda3/lib/python3.8/site-packages/nbclient/client.py", line 628, in _async_poll_for_reply
    await self._async_handle_timeout(timeout, cell)
  File "/Users/mpin/opt/miniconda3/lib/python3.8/site-packages/nbclient/client.py", line 678, in _async_handle_timeout
    raise CellTimeoutError.error_from_timeout_and_cell(
nbclient.exceptions.CellTimeoutError: A cell timed out while it was being executed, after 30 seconds.
The message was: Cell execution timed out.
Here is a preview of the cell contents:
-------------------
['%%capture', '', 'matplotlib_animation = topomap_3d_brain.animate_matplot_brain(', '    stc=stc,', '    views=views,']
...
['    cortex=cortex', ')', '', 'from IPython.display import HTML', 'video = HTML(matplotlib_animation.to_jshtml())']
-------------------

